### ISSUE TITLE
Set up testing

### ISSUE THREAD

**Issue by Mateusz-Dobrzynski** [debatecore/tau#16]
**Acceptance Criteria**
- `CONTRIBUTING.md` contains a requirement of covering code with tests – it needs to be established, which parts of code should be tested with integration and e2e tests,
- Additional frameworks are installed, if needed,
- A GitHub workflow running Rust tests is created.

**Comment by jakubmanczak** [comment]
`18-19-users-roles` on PR #24 has two tests running via cargo's integrated test suite.
